# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#0b0f11

# Main text color
theme[main_fg]=#dee7eb

# Title color for boxes
theme[title]=#dee7eb

# Highlight color for keyboard shortcuts
theme[hi_fg]=#a0cddf

# Background color of selected item in processes box
theme[selected_bg]=#141b1d

# Foreground color of selected item in processes box
theme[selected_fg]=#a0cddf

# Color of inactive/disabled text
theme[inactive_fg]=#6e777b

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#cdddff

# Background color of the percentage meters
theme[meter_bg]=#6e777b

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#cdddff

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#78c9fd
theme[mem_box]=#8beffc
theme[net_box]=#abbef0
theme[proc_box]=#6ac8f2

# Box divider line and small boxes line color
theme[div_line]=#40494d

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#8beffc
theme[temp_mid]=#d0f9f4
theme[temp_end]=#8ab5ff

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#a2ebfd
theme[cpu_mid]=#7bd3f3
theme[cpu_end]=#93d5fa

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#78c9fd
theme[free_mid]=#93d5fa
theme[free_end]=#6ac8f2

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#7bd3f3
theme[cached_mid]=#6ac8f2
theme[cached_end]=#93d5fa

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#a9daac
theme[available_mid]=#abbef0
theme[available_end]=#8ab5ff

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#8beffc
theme[used_mid]=#a2ebfd
theme[used_end]=#99e6ff

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#a9daac
theme[download_mid]=#abbef0
theme[download_end]=#8ab5ff

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#8beffc
theme[upload_mid]=#a2ebfd
theme[upload_end]=#99e6ff

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#7bd3f3
theme[process_mid]=#93d5fa
theme[process_end]=#78c9fd
