-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        border_size = 2,
    },
})

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = true,
})
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.06Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.exec_cmd("qs-overview toggle"))
hl.unbind("CTRL + SUPER + Left")
hl.bind("SUPER + CTRL + Left", hl.dsp.focus({ workspace = -1 }))
hl.unbind("CTRL + SUPER + Right")
hl.bind("SUPER + CTRL + Right", hl.dsp.focus({ workspace = "+1" }), {
    repeating = true,
})
